{% set name = "vinecopulib" %}
{% set version = "0.7.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ef514eaa4691186bb90c9e0490187342ffd89c2bb9d180ae8e36989c1dec8f20

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - libboost {{ boost }}
    - eigen 3.4.0
    - wdm 0.2.4
  run:
    - libboost {{ boost }}
    - eigen 3.4.0
    - wdm 0.2.6

test:
  requires:
    - {{ compiler('cxx') }}
  source_files:
    - examples/bicop

about:
  home: https://vinecopulib.github.io/vinecopulib
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: |
    A C++ library for vine copula models (w/ interfaces to R + Python)
  description: |
    A C++ library for vine copula models (w/ interfaces to R + Python)
  doc_url: https://vinecopulib.github.io/vinecopulib
  dev_url: https://github.com/vinecopulib/vinecopulib

extra:
  recipe-maintainers:
    - lorepirri
